name: CI/CD casino - Backend #a
on:
  push:
    branches: [ "deploy" ]

jobs:
  build-push-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR (runner)
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build imagen Backend y push a ECR
      run: |
        docker build -t casino-backend .
        docker tag casino-backend:latest ${{ secrets.ECR_REPO_URL_BACKEND }}:latest
        docker push ${{ secrets.ECR_REPO_URL_BACKEND }}:latest

    - name: Instalar psql y verificar
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client
        echo "psql location:" $(which psql || echo 'not found')
        psql --version || true

    - name: Levantar Contenedor de Base de Datos vía SSM
      run: |
        aws ssm send-command \
          --instance-ids ${{ secrets.EC2_DB_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --comment "Levantando Postgres" \
          --region ${{ secrets.AWS_REGION }} \
          --parameters '{"commands":[
            "docker pull postgres:latest",
            "docker stop casino-db || true",
            "docker rm casino-db || true",
            "docker run -d --name casino-db -p 5432:5432 -e POSTGRES_DB=${{ secrets.DB_NAME }} -e POSTGRES_USER=${{ secrets.DB_USER }} -e POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }} -v dbdata:/var/lib/postgresql postgres:latest",
            "sleep 10"
          ]}'
          
    - name: Desplegar Backend vía SSM
      run: |
        aws ssm send-command \
          --instance-ids ${{ secrets.EC2_BACKEND_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --comment "Despliegue con variables de entorno seguras" \
          --region ${{ secrets.AWS_REGION }} \
          --parameters '{"commands":[
            "set -e",
            "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
            "docker pull ${{ secrets.ECR_REPO_URL_BACKEND }}:latest",
            "docker stop casino-backend || true",
            "docker rm casino-backend || true",
            "docker run -d --name casino-backend -p 3000:3000 -e DB_HOST=${{ secrets.DB_PRIVATE_IP }} -e DB_USER=root -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_NAME=${{ secrets.DB_NAME }} ${{ secrets.ECR_REPO_URL_BACKEND }}:latest"
          ]}'
